my first hello world project
Simpleshaikh1/Microverse_Project pull request #2
Opened 2023-03-21 13:21 UTC by Simpleshaikh1

Created an index.html file that has h1 header file and a css file that change the text color

2023-03-21 13:43 UTC, Gambit142 requested changes
Hi @Simpleshaikh1 👋, 

Good job so far!

## Highlights
- It has HTML and CSS files ✔️ 
- The _**test.md**_ file is gitignored ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Could you use the recommended README.md file provided by Microverse? In the README.md file, you should personalize all sections to suit this project. The only optional section is the FAQ section. You can click on the link below to get the recommended README.md template

https://github.com/microverseinc/readme-template

_Kindly check the comments under the review for other required changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider making your commit messages more professional. A commit message should be written in imperative tense and capitalized as shown below:

![image](https://user-images.githubusercontent.com/77106962/226624434-f307e11a-3a3a-4b72-bf72-95c7ac702293.png)
 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-21 13:43 UTC, Gambit142 commented on .github/workflow/linter.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
- [ ] The GitHub actions do not check for the various linters that should be used for this project. Kindly follow this [article](https://github.com/microverseinc/linters-config/tree/master/html-css) to set up the linters for HTML and CSS projects. 👍 😎

2023-03-21 22:58 UTC, ouasamine requested changes
Hi @Simpleshaikh1 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

 ## Highlights
- Good PR title and description ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] Nice job adding the README to your project, however, it currently lacks a valid link to the LICENSE file, please add a LICENSE file to your project *(Microverse reminds using the MIT license)* and then add a link of that license file to your README under the License section at the bottom of the README.
- [ ] [OPTIONAL] It would be nice if you kept the table of content, because it makes it easy to navigate your README for other users, also using a smaller font size for your README content other than headers will make your README easier to read.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 22:58 UTC, ouasamine commented on .github/workflow/linter.yml
- [ ] As stated by the previous reviewer, the GitHub actions (linters checks) are currently not working and that is because the name of this file and its parent folder are actually wrong, it should be  `workflows` instead of `workflow` and `linters.yml` instead of `linter.yml`, please rename the file and the folder to set up the linters correctly.

2023-03-22 10:11 UTC, divinecharlotte requested changes
Hi @Simpleshaikh1   ,
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## To Highlight :100:

- Descriptive commit messages :heavy_check_mark:
- Descriptive PR :heavy_check_mark:
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes :recycle:

- [ ] kindly as requested by the previous reviewers consider setting up your linters correctly and make sure they meet the below requirements before you request for another reviewe
> - Linter should be set up correctly for this repository.
> - Linter result should be green. AKA: Linter should report NO errors.


_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 15:38 UTC, medaminedev66 commented
Hello @simpleshaikh 👋,

_This is an additional review as a result of the second opinion request._

I can see that you have a conflict on your PR. That's why the Linters checks do not show up. I recommend solving the conflict by following the steps below:
- Try to identify the files that have conflicts in your pull request.
- Fetch the latest changes from the upstream branch to your local branch. This can be done using the following commands in your terminal:
```php
git fetch upstream
git checkout <branch_name>
git merge upstream/<branch_name>
```
- Once the latest changes are fetched, you need to resolve the conflict by editing the files with conflicts. The conflicts are marked in the file with <<<<<<<, =======, and >>>>>>> markers. You need to manually edit the file to remove the markers and keep the relevant changes.
- Once the conflict is resolved, you need to add the changes to the staging area and commit them with a commit message explaining the changes.
```sql
Copy code
git add .
git commit -m "Resolved conflict on <file_name>"
```
- Finally, you need to push the changes to your branch in the remote repository.
```perl
git push origin <branch_name>
```
- Rebase the branch: If your branch is behind the upstream branch, you may need to rebase your branch on top of the upstream branch. This can be done using the following command:
```php
git rebase upstream/<branch_name>
```
After completing these steps, you should be able to resolve the conflict on your pull request.

When the conflict is solved, please ensure that you have no linters errors on your PR and Linter result is green, this means that the last commit has a green check mark (:white_check_mark:) or a summary of the passed checks is in the PR.

*If you still cannot solve the conflict, it's ok; no worries. You still can request a review and the next Code Reviewer will review your PR. But you still cannot merge your changes to the main branch if your PR is approved. That's why I highly recommend resolving the conflict.*

Keep rocking 🚀!

2023-03-23 00:22 UTC, braincee approved these changes
Hi @Simpleshaikh1  , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Kindly add the MIT Licence link as suggested by the previous reviewer to the README file.

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-23 00:46 UTC, merged

2023-03-27 07:51 UTC, LionRouge1 reviewed
Hi @Simpleshaikh1 , 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.